In [1]:
import pandas as pd
from scipy.io import wavfile
from scipy.signal import spectrogram
import glob
import re
import tqdm
import numpy as np

In [2]:
# Functions to sort file names correctly
def atoi(text):
    return int(text) if text.isdigit() else text

def natural_keys(text):
    return [atoi(c) for c in re.split(r'(\d+)', text)]

In [2]:
experiments = [384]
headmic_channels = [118,35]

In [ ]:
for exp in experiments:
    general_path = "D:/big_setup/experiment_{}/concatenated_data_cam_mic_sync/".format(exp)

    # getting the tracks
    track_files = glob.glob(general_path+"corrected_tracks/*.csv")
    track_files.sort(key=natural_keys)

    # getting the das files
    das_files = glob.glob(f"//sanesstorage.cns.nyu.edu/archive/Niegil/das/training_data/data/exp_{exp}*annotations.csv")
    das_files.sort(key=natural_keys)

    # getting the headmic files
    headmic_files = {}
    for idx in headmic_channels:
        temp_str = str(idx)
        headmic_files[idx] = glob.glob(general_path+f"headmic_{temp_str}_*.wav")
        headmic_files[idx].sort(key=natural_keys)


    length_of_experiment = len(glob.glob(general_path+"*.mp4"))
    powers = []
    powers_ = []

    for idx in tqdm.tqdm(range(length_of_experiment)):
        headmics = {}
        # getting the headmic channels
        for i in headmic_channels:
            file = headmic_files[i][idx]
            file_name = file.split("\\")[-1]
            if "%03d"%(idx) in file:
                sr,headmics[i] = wavfile.read(file)
            else:
                raise Exception(f"Error finding headmic file({file}) for idx {idx}")
        # getting the das file
        index = [id for id, s in enumerate(das_files) if "%03d"%(idx) in s]
        if len(index) == 1:
            file = das_files[index[0]]
            vox_times = pd.read_csv(file) 
        # pass
        else:
            print(f"Number of DAS files found for index {idx} is {len(index)}")
            raise Exception(f"More than one or less than one of das annotations files found for index {idx}")
        
        all_vox = []
        for vox_idx,start,stop in zip(vox_times[vox_times["name"]=="vox"].index,vox_times[vox_times["name"]=="vox"]["start_seconds"],vox_times[vox_times["name"]=="vox"]["stop_seconds"]):
            start_idx = int(sr*start)
            stop_idx = int(sr*stop)
            audio_0 = headmics[headmic_channels[0]][start_idx:stop_idx]
            audio_1 = headmics[headmic_channels[1]][start_idx:stop_idx]
            
            if (np.min(audio_0) == 0 and np.max(audio_0==0)) or (np.min(audio_1) == 0 and np.max(audio_1==0)):
                break



        
    

100%|██████████| 7/7 [00:01<00:00,  3.74it/s]


In [ ]:
noise_pwr_1/len(audio_1)*0.005*sr, noise_pwr_1

(1.9024102833812995e-07, 1.2181513526547139e-06)

([(0.0, 0.01498)],
 [(0.014976, 0.024964)],
 array([0.      , 0.002496, 0.004992, 0.007488, 0.009984, 0.01248 ,
        0.014976, 0.017472, 0.019968, 0.022464]),
 array([0.00846877, 0.00922422, 0.04389083, 0.06696201, 0.03601223,
        0.00896995, 0.00202441, 0.00376917, 0.00372696, 0.00111463]),
 0.006696200868916866)

In [184]:
len(audio_1_)

3663

In [185]:
3663/125000

0.029304

In [ ]:
3663

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [169]:
type(pow[-1])

numpy.float64

In [170]:
type(pow_thres)

numpy.float64

In [162]:
pow_thres

4.392488767825019e-06

In [129]:
audio_1

array([0., 0., 0., ..., 0., 0., 0.])

In [128]:

audio_1




"""sot
# Print results
for idx,(band, power) in enumerate(sorted_bands):"""
    

'sot\n# Print results\nfor idx,(band, power) in enumerate(sorted_bands):'

In [50]:
min_f,max_f

(22500, 35000)

In [20]:
x = np.atleast_2d(audio_0).T
events, segments, class_probabilities, class_names = das.predict.predict(x, 
                                                           model_save_name='D:/das/models/model_7.res/20251113_162500',
                                                           verbose=2,
                                                           segment_minlen=0.02,
                                                           segment_fillgap=0.01)

100%|██████████| 1/1 [00:00<00:00,  2.07it/s]


In [21]:
segments

{'samplerate_Hz': 125000.0,
 'index': array([0, 1, 2, 3, 4, 5, 6], dtype=int64),
 'names': ['noise',
  'combined',
  'combined_proposals',
  'noise',
  'noise_proposals',
  'vox',
  'vox_proposals'],
 'probabilities': array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.],
        [1., 0., 0., ..., 0., 0., 0.]]),
 'onsets_seconds': array([], dtype=float64),
 'offsets_seconds': array([], dtype=float64),
 'samples': array([0, 0, 0, ..., 0, 0, 0]),
 'sequence': array([], dtype=float64)}

In [22]:
audio_0

array([-3.991316 , -3.8691223, -3.8449757, ..., -3.9347608, -4.01436  ,
       -3.9584663], dtype=float32)

In [ ]:
for exp in experiments:
    # Reading the das file
    das = pd.read_csv()
